name: Vale Linting
on: [pull_request]

jobs:
  vale:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Vale
      uses: errata-ai/vale-action@reviewdog
      with:
        files: ${{ steps.changed_files.outputs.all_modified_files }}
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
